export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const VALIDAR_FORMULARIO_EXITO = 'VALIDAR_FORMULARIO_EXITO';
export const VALDIDAR_FORMULARIO_ERROR = 'VALIDAR_FORMULARIO_ERROR';

export const AGREGAR_PERSONA = 'AGREGAR_PERSONA';
export const AGREGAR_PERSONA_EXITO = 'AGREGAR_PERSONA_EXITO';
export const AGREGAR_PERSONA_ERROR = 'AGREGAR_PERSONA_ERROR';

export const COMENZAR_DESCARGA_PERSONAS = 'COMENZAR_DESCARGA_PERSONAS';
export const DESCARGA_PERSONAS_EXITOSA = 'DESCARGA_PERSONAS_EXITOSA';
export const DESCARGA_PERSONAS_ERROR = 'DESCARGA_PERSONAS_ERROR';