export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const VALIDAR_FORMULARIO_EXITO = 'VALIDAR_FORMULARIO_EXITO';
export const VALDIDAR_FORMULARIO_ERROR = 'VALIDAR_FORMULARIO_ERROR';

export const AGREGAR_PERSONA = 'AGREGAR_PERSONA';
export const AGREGAR_PERSONA_EXITO = 'AGREGAR_PERSONA_EXITO';
export const AGREGAR_PERSONA_ERROR = 'AGREGAR_PERSONA_ERROR';

export const COMENZAR_DESCARGA_PERSONAS = 'COMENZAR_DESCARGA_PERSONAS';
export const DESCARGA_PERSONAS_EXITOSA = 'DESCARGA_PERSONAS_EXITOSA';
export const DESCARGA_PERSONAS_ERROR = 'DESCARGA_PERSONAS_ERROR';

export const OBTENER_PERSONA_ELIMINAR = 'OBTENER_PERSONA_ELIMINAR';
export const PERSONA_ELIMINADA_EXITO = 'PERSONA_ELIMINADA_EXITO';
export const PERSONA_ELIMINADA_ERROR = 'PERSONA_ELIMINADA_ERROR';

export const OBTENER_PERSONA_EDITAR = 'OBTENER_PERSONA_EDITAR';
export const PERSONA_EDITAR_EXITO = 'PERSONA_EDITAR_EXITO';
export const PERSONA_EDITAR_ERROR = 'PERSONA_EDITAR_ERROR';

export const COMENZAR_EDICION_PERSONA = 'COMENZAR_EDICION_PERSONA';
export const PERSONA_EDITADA_EXITO = 'PERSONA_EDITADA_EXITO';
export const PERSONA_EDITADA_ERROR = 'PERSONA_EDITADA_ERROR';